test.todo( 'Point generates' );
test.todo( 'Snake generates' );
test.todo( 'Snake moves' );
test.todo( 'Snake turns' );
test.todo( 'Snake eats point' );
test.todo( 'Point respawns after eating' );
test.todo( 'Snake is bigger after eating point' );
test.todo( 'Snake is bigger' );
test.todo( 'Snake crashes into world bounds' );
test.todo( 'Snake crashes into himself' );
test.todo( 'Snake wins' );